version: '3'
services:

  #PHP Service
  app-sigesit:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel:php
    container_name: app-sigesit
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app-sigesit
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver-sigesit:
    image: nginx:alpine
    container_name: webserver-sigesit
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
